# Generated by Django 4.1.1 on 2022-09-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_remove_author_profile_pic_authorpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuthorPP',
        ),
    ]
