# Generated by Django 4.1.1 on 2022-09-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_profile_pic_delete_authorpp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='post',
        ),
    ]
